const size = {
  mobileS: "320px",
  mobileM: "375px",
  mobileL: "425px",
  mobileLExtraS: "470px",
  mobileLExtra: "560px",
  mobileXL: "768px",
  tablet: "900px",
  tabletM: "950px",
  laptop: "1024px",
  laptopS: "1200px",
  laptopM: "1300px",
  laptopXL: "1350px",
  desktop: "1450px",
};

export const device = {
  mobileS: `(max-width: ${size.mobileS})`,
  mobileM: `(max-width: ${size.mobileM})`,
  mobileL: `(max-width: ${size.mobileL})`,
  mobileLExtraS: `(max-width: ${size.mobileLExtraS})`,
  mobileLExtra: `(max-width: ${size.mobileLExtra})`,
  mobileXL: `(max-width: ${size.mobileXL})`,
  tablet: `(max-width: ${size.tablet})`,
  tabletM: `(max-width: ${size.tablet})`,
  laptop: `(max-width: ${size.laptop})`,
  laptopS: `(max-width: ${size.laptopS})`,
  laptopM: `(max-width: ${size.laptopM})`,
  laptopXL: `(max-width: ${size.laptopXL})`,
  desktop: `(max-width: ${size.desktop})`,
};
